"""try crud 2

Revision ID: c54f06f21585
Revises: b55f0dc5600d
Create Date: 2024-01-22 20:03:42.937298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54f06f21585'
down_revision: Union[str, None] = 'b55f0dc5600d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('submenu', sa.Integer(), nullable=True))
    op.drop_constraint('dish_menu_fkey', 'dish', type_='foreignkey')
    op.create_foreign_key(None, 'dish', 'submenu', ['submenu'], ['id'], ondelete='cascade')
    op.drop_column('dish', 'menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('menu', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.create_foreign_key('dish_menu_fkey', 'dish', 'submenu', ['menu'], ['id'], ondelete='CASCADE')
    op.drop_column('dish', 'submenu')
    # ### end Alembic commands ###
