"""try crud 4

Revision ID: c6c32c296676
Revises: 2dbadc5f6364
Create Date: 2024-01-22 23:18:23.432321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c32c296676'
down_revision: Union[str, None] = '2dbadc5f6364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('title', sa.String(), nullable=False))
    op.add_column('dish', sa.Column('description', sa.String(), nullable=False))
    op.add_column('dish', sa.Column('price', sa.Float(), nullable=False))
    op.drop_column('dish', 'name')
    op.add_column('submenu', sa.Column('title', sa.String(), nullable=False))
    op.add_column('submenu', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('submenu', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('submenu', 'description')
    op.drop_column('submenu', 'title')
    op.add_column('dish', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('dish', 'price')
    op.drop_column('dish', 'description')
    op.drop_column('dish', 'title')
    # ### end Alembic commands ###
